name: Build and Push Go WeatherApp

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.set-path.outputs.repo-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set path output (optional)
        id: set-path
        run: echo "repo-path=weather-app" >> $GITHUB_OUTPUT

  build-auth:
    name: Build Auth Service
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./weather-app/auth
          file: ./weather-app/auth/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/weather-auth:latest

  build-db:
    name: Build DB Service
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./weather-app/db
          file: ./weather-app/db/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/weather-db:latest

  build-redis:
    name: Build Redis Service
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./weather-app/redis
          file: ./weather-app/redis/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/weather-redis:latest

  build-ui:
    name: Build UI Service
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./weather-app/ui
          file: ./weather-app/ui/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/weather-ui:latest

  build-weather:
    name: Build Weather Service
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./weather-app/weather
          file: ./weather-app/weather/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/weather-weather:latest
